language: cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libmicrohttpd-dev libjsoncpp-dev libcurl4-openssl-dev libconfig++-dev libboost-signals-dev build-essential automake liblua5.1-0-dev

before_script:
    -  make
    - sudo sh master.sh 
